apiVersion: batch/v1
kind: CronJob
metadata:
  name: queue-precomputer-cron
spec:
  concurrencyPolicy: Forbid
  schedule: "39 3,11,19 * * *"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      # Terminate job if still running after 1 hour
      activeDeadlineSeconds: 3600
      # Delete finished job after a day
      ttlSecondsAfterFinished: 86400
      template:
        spec:
          securityContext:
            runAsNonRoot: true
          containers:
            - name: queue-precomputer
              image: "ghcr.io/ietf-tools/queue-precomputer:latest"
              imagePullPolicy: Always
              command: ['sh', '-c', 'node --experimental-transform-types ./src/job.ts']
              envFrom:
                - secretRef:
                    name: queue-secrets-env
              securityContext:
                allowPrivilegeEscalation: false
                capabilities:
                  drop:
                  - ALL
                readOnlyRootFilesystem: true
                runAsUser: 1000
                runAsGroup: 1000
          restartPolicy: Never
          terminationGracePeriodSeconds: 5